apiVersion: apps/v1
kind: Deployment
metadata:
  name: xp-springboot-oracle
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xp-springboot-oracle
  template:
    metadata:
      labels:
        app: xp-springboot-oracle
    spec:
      containers:
        - name: xp-springboot-oracle
          image: xp-springboot-oracle:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: xp-springboot-oracle-configmap
          env:
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: xp-springboot-oracle-secrets
                  key: SPRING_DATASOURCE_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: xp-springboot-oracle-secrets
                  key: SPRING_DATASOURCE_PASSWORD