apiVersion: apps/v1
kind: Deployment
metadata:
  name: xp-oracledb-aarch64
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xp-oracledb-aarch64
  template:
    metadata:
      labels:
        app: xp-oracledb-aarch64
    spec:
      containers:
        - name: xp-oracledb-aarch64
          image: xp-oracledb-aarch64:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 1521
          env:
            - name: ORACLE_PWD
              valueFrom:
                secretKeyRef:
                  name: xp-oracledb-aarch64-secrets
                  key: ORACLE_PWD
            - name: ORACLE_SID
              value: ORCLCDB
            - name: ORACLE_PDB
              value: ORCLPDB1
            - name: ORACLE_CHARACTERSET
              value: AL32UTF8